### Create a doctor
POST http://localhost:9090/hospital/doctors
Content-Type: application/json

{
    "id": 6,
    "name": "Test Doctor",
    "specialty": "Physician",
    "phoneNumber": "1234567890"
}

### Create a patient
POST http://localhost:9090/hospital/patients
Content-Type: application/json

{
    "name": "Jane TEST TEST",
    "age": 30,
    "phoneNumber": "0771690000",
    "gender": "FEMALE",
    "address": "154, Secondary Street, Colombo 05"
}

### Create an appointment
POST http://localhost:9090/hospital/appointments
Content-Type: application/json

{
    "id": 14,
    "_patientId": 6,
    "_doctorId": 6,
    "appointmentTime": {
        "year": 2023,
        "month": 07,
        "day": 01,
        "hour": 10,
        "minute": 30
    },
    "status": "SCHEDULED",
    "reason": "Fever"
}

//this
### Get all appointments for doctor 01 on 2023-07-01
GET http://localhost:9090/hospital/doctors/6/appointments?year=2023&month=07&day=01

### Get all doctors with specialty
GET http://localhost:9090/hospital/doctors

### Get patient details by id
GET http://localhost:9090/hospital/patients/12


### Update the status of the appointment
PATCH  http://localhost:9090/hospital/appointments/14
Content-Type: application/json

"STARTED"

//this
### Delete an appointment
DELETE http://localhost:9090/hospital/patients/6/appointments?year=2023&month=07&day=01

